### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by JohnnyEstilles** [idottv/dependable#31]
I haven't seen any activity for 5 months or so. I'm interesting in contributing some ideas. However, if the project has been abandoned, we may consider spinning off a new project based on `dependable`.

**Comment by templaedhel** [comment]
@JohnnyEstilles Let me/us (https://github.com/Clever) know if you do - we're currently using this project in a few places and if there was a version being maintained we'd switch to that.

**Comment by JohnnyEstilles** [comment]
@templaedhel, it is definitely my intention to do so. Out of professional courtesy, I will leave this issue open for a week or so. I want to make sure the repo's contributors no longer have any interest in maintaining it.

If there's not response from the contributors in a reasonable amount of time, I will create a new repo and continue development/maintenance. I will also let you can @clever know when I do.

**Comment by shrew-io** [comment]
@JohnnyEstilles I am also genuinely interested if you are going to fork the project. Let us know in this issue.

**Comment by JohnnyEstilles** [comment]
@shrew-io, I am already working on a similar project. I'm trying to make sure the initial version is 100% compatible with `dependable`, but it will have a few additional l features I use/need for my projects.

[nject](https://github.com/autoric/nject) is a nice little framework, but it did not satisfy my needs. `dependable` did for a while, but we outgrew its current capabilities. I was hoping to contribute to the project, but it appears to be abandoned.

For all of those interested, I will post a comment here when I publish the initial version of my project.

**Comment by JohnnyEstilles** [comment]
Closing due to lack of response from repo owner and collaborators.

See issue #32 if your interested in my upcoming, dependable-inspired project.
