### ISSUE TITLE
NEW: agentia-asset-manager (a dependable-inspired, dependency injection framework)

### ISSUE THREAD

**Issue by JohnnyEstilles** [idottv/dependable#32]
![agentia-asset-manager][logo]
---
I'm really sad that `dependable` is no longer being maintained. The project definitely had a lot of potential.

However, life goes on, and we need new toys with which to play. So, as I mentioned in issue #31, I've been working on a dependable-inspired, dependency injection framework. I've completed alpha testing, and am know publishing it on [GH][repo] for beta testing.

Check out the repo at: https://github.com/AgentiaSystems/agentia-asset-manager. Feel free to poke around and try it out.

### How to Install
It is not yet available on npm, but you can install directly from the master branch using:

```
npm install --save AgentiaSystems/agentia-asset-manager
```

### TODO
I still have some work before officially releasing it.
- Complete beta testing (hopefully with your feedback)
- Proofread/tweak to README
- add coding standards
- add contribution guidelines
- publish to npm

Your feedback will be greatly appreciated.

[logo]: https://raw.githubusercontent.com/AgentiaSystems/agentia-asset-manager/master/media/logo.png
[repo]: https://github.com/AgentiaSystems/agentia-asset-manager.

**Comment by shrew-io** [comment]
Super awesome work @JohnnyEstilles! I really appreciate your inspired framework and love the documentation.

**Comment by JohnnyEstilles** [comment]
@shrew-io ... Thanks! It still needs some tweaking, but I hope to have a releasable version by the end of next week. I will keep you all posted.

Have you been able to test it?

**Comment by JohnnyEstilles** [comment]
Sorry everyone, I had to rename to project from `agentia-modular` to `agentia-asset-manager`. `agentia-modular` is actually the name of another one of our projects.

**Comment by JohnnyEstilles** [comment]
I've published the initial version of [agentia-asset-manager](https://github.com/AgentiaSystems/agentia-asset-manager) to [npm](https://npmjs.org/package/agentia-asset-manager). Thank you to all who should interest in my project.
